//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class datagapstab
    {
        public int bolus_id { get; set; }
        public double temperature { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
    }
}
