//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string page { get; set; }
        public string function_query { get; set; }
        public string error { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> datestamp { get; set; }
        public string recipient { get; set; }
    }
}
