//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SETTINGS
    {
        public int ID { get; set; }
        public string SP_CODE { get; set; }
        public string SP_NAME { get; set; }
    }
}
