//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCabinet
    {
        public int id { get; set; }
        public string AspNetUsersID { get; set; }
        public string Email { get; set; }
        public bool AlertTemperatureInd { get; set; }
        public bool AlertWaterIntakesInd { get; set; }
        public bool AlertOutOfRangeInd { get; set; }
        public string ReportAnimalsIdList { get; set; }
        public bool ReportTempChartInd { get; set; }
        public bool ReportStatInd { get; set; }
    }
}
